spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUniqueEncoding=true&characterEncoding=utf-8
    username: root
    password: luozhiwei1234
